# vim: ft=ghostty
# Jet Black theme for Ghostty
# Scheme Author: rudra (derived from Pitch Black by Viktor Qvarfordt)
# Scheme System: base24
# Template Author: Tinted Terminal (https://github.com/tinted-theming/tinted-terminal)

# Color palette
palette = 0=#000000
palette = 1=#ff827a
palette = 2=#a8d57e
palette = 3=#d0c590
palette = 4=#70b7f6
palette = 5=#d293cd
palette = 6=#64c1b0
palette = 7=#d4d4d4
palette = 8=#666666
palette = 9=#ff9894
palette = 10=#c5e88b
palette = 11=#e8dc7f
palette = 12=#86ceff
palette = 13=#dd99ff
palette = 14=#72d4c0
palette = 15=#ffffff
palette = 16=#ff9652
palette = 17=#d7ba7d
palette = 18=#1a1a1a
palette = 19=#2a2a2a
palette = 20=#808080
palette = 21=#e8e8e8

# Foreground & background colors
background = #000000
foreground = #d4d4d4
cursor-color = #d4d4d4
selection-background = #d4d4d4
selection-foreground = #2a2a2a
search-background = #d0c590
search-foreground = #1a1a1a
search-selected-background = #ff9652
search-selected-foreground = #1a1a1a

# Set `macos-icon = custom-style` in your main configuration file to enable theming of the app icon.
#
# Set the ghost color to the lightest foreground:
macos-icon-ghost-color = #ffffff
# Replace the official icon's blue background with the designated bright blue color:
macos-icon-screen-color = #86ceff
